auth:
  cache-ttl-secs: 300
  token-review-audiences: []

prometheus:
  listener:
    host: 0.0.0.0
    port: 9090

grpc:
  listener:
    host: 0.0.0.0
    port: 50051
  upstream:
    host: 127.0.0.1
    port: 50052
  rules:
    - name: flight
      request:
        service: arrow.flight.protocol.FlightService
        grpc-methods:
          - DoAction
          - DoGet
          - GetFlightInfo
        headers:
          - name: "x-tenant-id"
            value: "{tenant-id}"
      access:
        sar-resource-attributes:
          namespace: "{tenant-id}"
          api-group: dataconnecthub.opendatahub.io
          resource: data-store
          verb: "get"

http:
  listener:
    host: 0.0.0.0
    port: 8080

  upstream:
    host: 127.0.0.1
    port: 8081
  rules:
    - name: rest
      request:
        path: /api/v1alpha1/data/connections
        headers:
          - name: "x-tenant-id"
            value: "{tenant-id}"
        methods:
          - post
      access:
        sar-resource-attributes:
          namespace: "{tenant-id}"
          api-group: dataconnecthub.opendatahub.io
          resource: data-connections
          verb: "create"

    - name: no-auth
      request:
        path: /health
        headers:
          - name: "x-tenant-id"
            value: "{tenant-id}"
        methods:
          - post
      access: no-auth
