
server:
  host: 0.0.0.0
  port: 6188
  ssl: false
  cert_file: ""
  key_file: ""

auth:
  cache-ttl-secs: 300
  token-review-audiences: []

grpc:
  upstream:
    host: 127.0.0.1
    port: 50051
  mappings:
    - name: flight
      conditions:
        service: arrow.flight.protocol.FlightService
        grpc-methods:
          - DoAction
          - DoGet
          - GetFlightInfo
        headers:
          - name: "x-tenant-id"
            value: "{tenant-id}"

      sar-resource-attributes:
        namespace: "{tenant-id}"
        api-group: dataconnecthub.opendatahub.io
        resource: data-store
        verb: "get"

http:
  upstream:
    host: 127.0.0.1
    port: 8081
  mappings:
    - name: rest
      conditions:
        path: /api/v1alpha1/data/connections
        headers:
          - name: "x-tenant-id"
            value: "{tenant-id}"
        methods:
          - post

      sar-resource-attributes:
        namespace: "{tenant-id}"
        api-group: dataconnecthub.opendatahub.io
        resource: data-connections
        verb: "create"


